### ISSUE TITLE
cannot get  access to s3 object

### ISSUE THREAD

**Issue by xinzhel** [facebookresearch/text-adversarial-attack#2]
hi, dear authors,

I want to download the model by running the provided script:
```
 s3cmd get s3://dl.fbaipublicfiles.com/text-adversarial-attack/transformer_wikitext-103.pth result/
```

But the error occurs _**ERROR: S3 error: 403 (AccessDenied): Access Denied**_ . 
It may be the problem of the IAM policy. If it is, could you change it for open downloading?
If not, would you have any suggestions for any other problems which may happen on my side? (I am not very familiar with AWS S3 storage service)

BTW, thank you for open-sourcing your awesome works.

Regards,
Xinzhe

**Comment by alexandresablayrolles** [comment]
Hi xinzhel,
Thanks for reporting the issue. This should work:
```
curl https://dl.fbaipublicfiles.com/text-adversarial-attack/transformer_wikitext-103.pth -o transformer_wikitext-103.pth
```
Closing the issue, feel free to re-open if it doesn't work for you
