### ISSUE TITLE
USE error

### ISSUE THREAD

**Issue by sullendhy** [facebookresearch/text-adversarial-attack#5]
hello, when i load USE from local file, error occurs "
Graph execution error:
JIT compilation failed.
	 [[{{node EncoderDNN/EmbeddingLookup/EmbeddingLookupUnique/embedding_lookup/mod}}]] "

![image](https://user-images.githubusercontent.com/82580782/187055794-fba33416-7fec-4912-bd3b-33c17453b5f5.png)

**Comment by sullendhy** [comment]
Thanks for your great job. I have solved problem i mentioned above by switching to the cpu device.
But i have another question, it seemed that the code did not show the accuracy of white-box attack, and it only give the performace of transfer attack in "evaluate_adv_samples.py". I am not sure whether my understanding is correct. 
Anyway, thanks very much, i've learned a lot. Best wishes

**Comment by cg563** [comment]
Sorry for the late response on the previous issue.

If you set the `model` argument in `evaluate_adv_samples.py` to be the same as the `model` argument in `whitebox_attack.py`, that will correspond to a white-box attack since the adversarial text distribution is optimized on the same model.

**Comment by sullendhy** [comment]
I see. Thanks for your patience and excellent work. Best wishes from China.
